/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InvestissementsRouteImport } from './routes/investissements'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ObjectifsRouteImport } from './routes/objectifs'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PortefeuilleRouteImport } from './routes/portefeuille'
import { Route as ProjectionsRouteImport } from './routes/projections'
import { Route as RevenusRouteImport } from './routes/revenus'
import { Route as TransactionsRouteImport } from './routes/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestissementsRoute = InvestissementsRouteImport.update({
  id: '/investissements',
  path: '/investissements',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectifsRoute = ObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefeuilleRoute = PortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenusRoute = RevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/investissements': typeof InvestissementsRoute
  '/journal': typeof JournalRoute
  '/objectifs': typeof ObjectifsRoute
  '/parametres': typeof ParametresRoute
  '/performance': typeof PerformanceRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/projections': typeof ProjectionsRoute
  '/revenus': typeof RevenusRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/investissements': typeof InvestissementsRoute
  '/journal': typeof JournalRoute
  '/objectifs': typeof ObjectifsRoute
  '/parametres': typeof ParametresRoute
  '/performance': typeof PerformanceRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/projections': typeof ProjectionsRoute
  '/revenus': typeof RevenusRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/investissements': typeof InvestissementsRoute
  '/journal': typeof JournalRoute
  '/objectifs': typeof ObjectifsRoute
  '/parametres': typeof ParametresRoute
  '/performance': typeof PerformanceRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/projections': typeof ProjectionsRoute
  '/revenus': typeof RevenusRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/auth'
    | '/import'
    | '/investissements'
    | '/journal'
    | '/objectifs'
    | '/parametres'
    | '/performance'
    | '/portefeuille'
    | '/projections'
    | '/revenus'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/auth'
    | '/import'
    | '/investissements'
    | '/journal'
    | '/objectifs'
    | '/parametres'
    | '/performance'
    | '/portefeuille'
    | '/projections'
    | '/revenus'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/auth'
    | '/import'
    | '/investissements'
    | '/journal'
    | '/objectifs'
    | '/parametres'
    | '/performance'
    | '/portefeuille'
    | '/projections'
    | '/revenus'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  AuthRoute: typeof AuthRoute
  ImportRoute: typeof ImportRoute
  InvestissementsRoute: typeof InvestissementsRoute
  JournalRoute: typeof JournalRoute
  ObjectifsRoute: typeof ObjectifsRoute
  ParametresRoute: typeof ParametresRoute
  PerformanceRoute: typeof PerformanceRoute
  PortefeuilleRoute: typeof PortefeuilleRoute
  ProjectionsRoute: typeof ProjectionsRoute
  RevenusRoute: typeof RevenusRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investissements': {
      id: '/investissements'
      path: '/investissements'
      fullPath: '/investissements'
      preLoaderRoute: typeof InvestissementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectifs': {
      id: '/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof ObjectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefeuille': {
      id: '/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof PortefeuilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenus': {
      id: '/revenus'
      path: '/revenus'
      fullPath: '/revenus'
      preLoaderRoute: typeof RevenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  AuthRoute: AuthRoute,
  ImportRoute: ImportRoute,
  InvestissementsRoute: InvestissementsRoute,
  JournalRoute: JournalRoute,
  ObjectifsRoute: ObjectifsRoute,
  ParametresRoute: ParametresRoute,
  PerformanceRoute: PerformanceRoute,
  PortefeuilleRoute: PortefeuilleRoute,
  ProjectionsRoute: ProjectionsRoute,
  RevenusRoute: RevenusRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
